app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::get('/', ['as' => 'dashboard.index', 'uses' => 'DashboardController@index']);
Route::get('/notifications', ['as' => 'dashboard.notifications', 'uses' => 'DashboardController@notifications']);

Route::get('login', 'AuthController@showLogin');
Route::post('login', 'AuthController@postLogin');
Route::get('logout', 'AuthController@getLogout');

Route::get('/scorecards/current', ['as' => 'scorecards.current', 'uses' => 'ScorecardsController@current']);
Route::post('accomplishments/', ['as' => 'accomplishments.index', 'uses' => 'AccomplishmentsController@index']);
Route::get('accomplishments/{year}', ['as' => 'accomplishments.year', 'uses' => 'AccomplishmentsController@year']);
Route::get('sample/{year}', ['as' => 'accomplishments.sample', 'uses' => 'AccomplishmentsController@sample']);
Route::get('accomplishments/{year}/{quarter}', ['as' => 'accomplishments.quarter', 'uses' => 'AccomplishmentsController@quarter']);

Route::get('/report/sg/{id}', ['as' => 'report.generate', 'uses' => 'ReportController@generateSG']);

Route::get('/visionbc', function()
{
	return View::make('masterSC.visionbc');
});

Route::get('/measure/{id}', ['as' => 'measure.show', 'uses' => 'MeasureController@show']);

Route::group(['before' => 'role:0'], function()
{
	Route::get('/scorecards', ['as' => 'scorecards.index', 'uses' => 'ScorecardsController@index']);
	Route::get('/scorecards/create', ['as' => 'scorecards.create', 'uses' => 'ScorecardsController@create']);
	Route::post('/scorecards', ['as' => 'scorecards.store', 'uses' => 'ScorecardsController@store']);
	Route::get('/scorecards/{id}/edit', ['as' => 'scorecards.edit', 'uses' => 'ScorecardsController@edit']);
	Route::post('/scorecards/{id}/edit', ['as' => 'scorecards.update', 'uses' => 'ScorecardsController@update']);
	Route::get('scorecard/setcurrent/{id}', ['as' => 'scorecards.setcurrent', 'uses' => 'ScorecardsController@setcurrent']);
	Route::get('scorecard/setarchive/{id}', ['as' => 'scorecards.setarchive', 'uses' => 'ScorecardsController@setarchive']);
	Route::get('scorecard/unsetarchive/{id}', ['as' => 'scorecards.unsetarchive', 'uses' => 'ScorecardsController@unsetarchive']);
	Route::get('scorecard/archives', ['as' => 'scorecards.archives', 'uses' => 'ScorecardsController@archives']);

	Route::get('/manageperspective', ['as' => 'perspectives.index', 'uses' => 'PerspectivesController@index']);
	Route::post('/manageperspective', ['as' => 'perspectives.store', 'uses' => 'PerspectivesController@store']);
	Route::get('perspective/sethighest/{id}', ['as' => 'perspectives.setHighest', 'uses' => 'PerspectivesController@setHighest']);
	Route::get('perspective/delete/{id}',['as' => 'perspectives.delete', 'uses' => 'PerspectivesController@delete']);
	Route::post('perspective/{id}/edit', ['as' => 'perspectives.update', 'uses' => 'PerspectivesController@update']);

	Route::get('/managestratobj',  ['as' => 'objectives.index', 'uses' => 'ObjectivesController@index'] );
	Route::post('/objectives', ['as' => 'objectives.store', 'uses' => 'ObjectivesController@store']);
	Route::post('/objectives/{o_id}/edit',['as' => 'objectives.update', 'uses' => 'ObjectivesController@update']);
	Route::get('/objectives/{o_id}/delete', ['as' => 'objectives.delete', 'uses' => 'ObjectivesController@delete']);
	Route::post('objectives/{id}/{pid}/move', ['as' => 'objectives.move', 'uses' => 'ObjectivesController@move']);

	Route::get('/measurelist', ['as' => 'measure.index', 'uses' => 'MeasureController@index']);
	Route::get('/measure/{id}/edit', ['as' => 'measure.edit', 'uses' => 'MeasureController@edit']);
	Route::get('/measure/setasfinal/{id}', ['as' => 'measure.setFinal', 'uses' => 'MeasureController@setFinal']);
	Route::get('/measure/unsetasfinal/{id}', ['as' => 'measure.setDraft', 'uses' => 'MeasureController@setDraft']);
	Route::post('/measure/save/{id}', ['as' => 'measure.update', 'uses' => 'MeasureController@update']);
	Route::get('/measure/delete/{id}', ['as' => 'measure.destroy', 'uses' => 'MeasureController@destroy']);

	Route::get('/initiative/create', ['as' => 'initiatives.create', 'uses' => 'InitiativesController@create']);
	Route::post('/initiative', ['as' => 'initiatives.store', 'uses' => 'InitiativesController@store']);
	Route::get('initiatives/setfinal/{id}', ['as' => 'initiatives.setFinal', 'uses' => 'InitiativesController@setFinal']);
	Route::get('initiatives/unsetfinal/{id}', ['as' => 'initiatives.setDraft', 'uses' => 'InitiativesController@setDraft']);
	Route::get('initiatives/delete/{id}', ['as' => 'initiatives.delete', 'uses' => 'InitiativesController@delete']);

	Route::get("/indicators/goal/", ['as' => 'indicators.index', 'uses' => 'IndicatorsController@index']);
	Route::post("/indicators/goal/store", ['as' => 'indicators.store', 'uses' => 'IndicatorsController@store']);
	Route::post("/indicators/goal/{id}/update", ['as' => 'indicators.update', 'uses' => 'IndicatorsController@update']);
	Route::get("/indicators/goal/{id}/delete", ['as' => 'indicators.destroy', 'uses' => 'IndicatorsController@destroy']);
	Route::get("/goals/{gid}/indicator/{id}/move/up", ['as' => 'indicators.moveUp', 'uses' => 'IndicatorsController@moveUp']);
	Route::get("/goals/{gid}/indicator/{id}/move/down", ['as' => 'indicators.moveDown', 'uses' => 'IndicatorsController@moveDown']);
	Route::post("/goals/{id}/indicators/aggregation/", ['as' => 'indicators.aggregation', 'uses' => 'IndicatorsController@aggregation']);

	Route::get("/indicators/obj/{id}", ['as' => 'indicators.index2', 'uses' => 'IndicatorsController@index2']);

	Route::get('/users', ['as' => 'users.index', 'uses' => 'UsersController@index']);
	Route::get('/createuser', ['as' => 'users.create', 'uses' => 'UsersController@create']);
	Route::post('/createuser', ['as' => 'users.store', 'uses' => 'UsersController@store']);
	Route::get('/edit/{id}', ['as' => 'users.edit', 'uses' => 'UsersController@edit']);
	Route::post('/edituser/{id}', ['as' => 'users.update', 'uses' => 'UsersController@update']);

	Route::resource('createoffice','OfficeController');
	Route::resource('offices','OfficeController');
	
	Route::get('/officesb/central/unsetasfinal/{id}', ['as' => 'sb.centralUnsetfinal', 'uses' => 'ScoreboardController@centralUnsetfinal']);
	
	Route::get('/officesb/field/unsetasfinal/{id}', ['as' => 'sb.fieldUnsetfinal', 'uses' => 'ScoreboardController@fieldUnsetfinal']);

	Route::get('/systemsettings', ['as' => 'systemsettings.index', 'uses' => 'SystemSettingsController@index']);
	Route::get('/systemsettings/managestrategymap', ['as' => 'systemsettings.stratmap', 'uses' => 'SystemSettingsController@stratmap']);
	Route::post('/systemsettings/upload', ['as' => 'systemsettings.upload', 'uses' => 'SystemSettingsController@upload']);
	Route::get('/systemsettings/change/{id}', ['as' => 'systemsettings.change', 'uses' => 'SystemSettingsController@change']);
	Route::get('/systemsettings/aggregate', ['as' => 'systemsettings.aggregate', 'uses' => 'SystemSettingsController@aggregate']);
});

Route::group(['before' => 'role:013'], function()
{
	Route::get('/officesb', ['as' => 'sb.index', 'uses' => 'ScoreboardController@index']);
	Route::get('/officesb/field/createsb/{month}/{year}', ['as' => 'sb.fieldCreate', 'uses' => 'ScoreboardController@fieldCreate']);
	Route::get('/officesb/field/sbedit/{id}', ['as' => 'sb.fieldEdit', 'uses' => 'ScoreboardController@fieldEdit']);
	Route::post('/officesb/field/updatesb/{id}',['as' => 'sb.fieldUpdate', 'uses' => 'ScoreboardController@fieldUpdate']);
	Route::post('/officesb/field/{id}/remark',['as' => 'sb.fieldRemark', 'uses' => 'ScoreboardController@fieldRemark']);
	Route::get('/officesb/field/showsb/{id}', ['as' => 'sb.fieldShow', 'uses' => 'ScoreboardController@fieldShow']);
	Route::get('/officesb/field/forapproval/{id}',['as' => 'sb.fieldSetfinal', 'uses' => 'ScoreboardController@fieldApproval'] );
	Route::get('/officesb/field/setasfinal/{id}',['as' => 'sb.fieldSetfinal', 'uses' => 'ScoreboardController@fieldSetfinal'] );
	Route::post('/officesb/field/createsb/store', ['as' => 'sb.fieldStore', 'uses' => 'ScoreboardController@fieldStore']);
	Route::get('/officesb/field/delete/{id}', ['as' => 'sb.fieldDelete', 'uses' => 'ScoreboardController@fieldDelete']);
});


Route::group(['before' => 'role:024'], function()
{
	Route::get('/officesb/central/', ['as' => 'sb.central', 'uses' => 'ScoreboardController@central']);
	Route::get('/officesb/central/createsb/{month}/{year}', ['as' => 'sb.centralCreate', 'uses' => 'ScoreboardController@centralCreate']);
	Route::get('/officesb/central/showsb/{id}', ['as' => 'sb.centralShow', 'uses' => 'ScoreboardController@centralShow']);
	Route::post('/officesb/central/createsb/store', ['as' => 'sb.centralStore', 'uses' => 'ScoreboardController@centralStore']);
	Route::get('/officesb/central/sbedit/{id}', ['as' => 'sb.centralEdit', 'uses' => 'ScoreboardController@centralEdit']);
	Route::post('/officesb/central/updatesb/{id}',['as' => 'sb.centralUpdate', 'uses' => 'ScoreboardController@centralUpdate']);
	Route::post('/officesb/central/{id}/remark',['as' => 'sb.centralRemark', 'uses' => 'ScoreboardController@centralRemark']);
	Route::get('/officesb/central/delete/{id}', ['as' => 'sb.centralDelete', 'uses' => 'ScoreboardController@centralDelete']);
	Route::get('/officesb/central/forapproval/{id}', ['as' => 'sb.centralSetfinal', 'uses' => 'ScoreboardController@centralApproval'] );
	Route::get('/officesb/central/setasfinal/{id}', ['as' => 'sb.centralSetfinal', 'uses' => 'ScoreboardController@centralSetfinal'] );
});

Route::group(['before' => 'role:012345'], function()
{

app/views/administration/createoffice.blade.php
@extends('layouts.default')
@section('content')
	<h2>Create New Office</h2>
	<hr />
	{{ Form::open(['route'=>'createoffice.store'],'POST') }}
		<div class="row">
			<div class="col-md-6">	
			<div class="form-group">
				{{ Form::label('office_abbreviation', 'Office Abbreviation: * ') }}{{ $errors->first('office_abbreviation', '<span class=errormsg>:message</span>') }}
				<br>
				{{ Form::text('office_abbreviation','',['class'=>'form-control'])}}
			</div>

			<div class="form-group">
				{{ Form::label('office_name', 'Office Name: * ') }}{{ $errors->first('office_name', '<span class=errormsg>:message</span>') }}
				<br>
				{{ Form::text('office_name','',['class'=>'form-control'])}}
			</div>

			

			<div class="form-group">
				{{ Form::label('office_type', 'Office Type: * ') }}{{ $errors->first('office_type', '<span class=errormsg>:message</span>') }}
				<br>
				{{ Form::radio('office_type', 'Central Office', ['selected'=>'selected']) }} Central Office<br>
				{{ Form::radio('office_type', 'Field Office') }} Field Office
			</div>
			
			<button type="submit" name="create1" class="btn btn-primary" value="create">Create Office</button>
			<button type="submit" name="create2"class="btn btn-default" value="another">Create and Create Another</button>
			{{ link_to( '/offices', 'Cancel', array('class'=>'btn btn-default') ) }}

			</div>
			</div>	
    		
    			
	{{ Form::close() }}	

@stop

app/views/administration/createuser.blade.php
@extends('layouts.default')
@section('content')
	<h2>Create User Account</h2>
	<hr />
	{{ Form::open(['url' => '/createuser', 'name' => 'create1', 'class' => 'form-horizontal col-md-6', 'role' => 'form']) }}
		<div class = "form-group">
			{{ Form::label('username', 'Username: *'); }}
			{{ $errors->first('username', '<span class=errormsg>*:message</span>') }}
			{{ Form::text('username', null, ['class' => 'form-control']) }}
		</div>
		<div class = "form-group">
		{{ Form::label('firstName', 'First Name: *'); }}
		{{ $errors->first('first_name', '<span class=errormsg>*:message</span>') }}
		{{ Form::text('first_name', null, ['class' => 'form-control']) }}
		</div>
		<div class = "form-group">
		{{ Form::label('lastName', 'Last Name: *'); }}
		{{ $errors->first('last_name', '<span class=errormsg>*:message</span>') }}
		{{ Form::text('last_name', null, ['class' => 'form-control']) }}
		</div>
		<div class = "form-group">
		{{ Form::label('email', 'Email Address: *'); }}
		{{ $errors->first('email', '<span class=errormsg>*:message</span>') }}
		{{ Form::email('email', null, ['class' => 'form-control']) }}
		</div>
		<div class = "form-group">
		{{ Form::label('password', 'Password: *'); }}
		{{ $errors->first('password', '<span class=errormsg>*:message</span>') }}
		{{ Form::password('password', ['class' => 'form-control']) }}
		</div>
		<div class = "form-group">
			{{ Form::label('cpassword', 'Confirm Password: *'); }}
			{{ $errors->first('cpassword', '<span class=errormsg>*:message</span>') }}
			{{ Form::password('cpassword', ['class' => 'form-control']) }}
		</div>
		<div class = "form-group">
				{{ Form::label('role', 'Role: *'); }}
				{{ $errors->first('role', '<span class=errormsg>*:message</span>') }}
				{{ Form::select('role', $roles, null, ['id' => 'roles', 'class' => 'form-control roles']) }}
		</div>
		<div id="osm" class="form-group">
			{{ Form::label('offices', 'Office:'); }}
			{{ $errors->first('office', '<span class=errormsg>*:message</span>') }}
			{{ Form::select('office[]', $osm, null, ['class' => 'form-control offices']) }}
		</div>
		<div id="fo" class="form-group">
			{{ Form::label('offices', 'Office:'); }}
			{{ $errors->first('office', '<span class=errormsg>*:message</span>') }}
			{{ Form::select('office[]', $fo, null, ['class' => 'form-control offices']) }}
		</div>
		<div id="co" class="form-group">
			{{ Form::label('offices', 'Office:'); }}
			{{ $errors->first('office', '<span class=errormsg>*:message</span>') }}
			{{ Form::select('office[]', $co, null, ['class' => 'form-control offices']) }}
		</div>
		<div class = "form-inline form-group">
			{{ Form::submit('Create User', ['name' => 'create1', 'class' => 'btn btn-primary', 'id' => 'create1']) }}
			{{ Form::submit('Create and Create Another', ['name' => 'create2', 'class' => 'btn btn-default', 'id' => 'create2']) }}
			{{ link_to( '/users', 'Cancel', array('class'=>'btn btn-default') ) }}
		</div>
	{{ Form::close() }}
	{{ Form::close() }}
@stop

@section('cssjs')
<script type="text/javascript">
    $(document).ready(function() {
    	switch($('#roles').val())
    	{
    		case '0': 
    			$('#osm').show();
    			$('#fo').hide();
    			$('#co').hide();
			break;
    		case '1': 
    		case '3':
    			$('#osm').hide();
    			$('#fo').show();
    			$('#co').hide();
			break;
    		case '2': 
    		case '4':
    			$('#osm').hide();
    			$('#fo').hide();
    			$('#co').show();
			break;
			case '5':
    			$('#osm').hide();
    			$('#fo').hide();
    			$('#co').hide();
    		break;
    	}
        $('#roles').change(function(event) {
        	switch($(this).val())
        	{
        		case '0': 
        			$('#osm').show();
        			$('#fo').hide();
        			$('#co').hide();
    			break;
        		case '1': 
        		case '3':
        			$('#osm').hide();
        			$('#fo').show();
        			$('#co').hide();
    			break;
        		case '2': 
        		case '4':
        			$('#osm').hide();
        			$('#fo').hide();
        			$('#co').show();
    			break;
				case '5':
	    			$('#osm').hide();
	    			$('#fo').hide();
	    			$('#co').hide();
	    		break;
        	}
        });
    });
</script>
@stop

app/views/administration/editoffice.blade.php
@extends('layouts.default')
@section('content')
	<h2>Edit Office</h2>
	<hr />

	<div class="row">
		<div class="col-md-6">	
			{{ Form::model($office, array('route' => array('createoffice.update', $office->id), 'method' => 'PUT')) }}

			<div class="form-group">
				{{ Form::label('office_abbreviation', 'Office Abbreviation:') }}
				{{ Form::text('office_abbreviation', $office->office_abbreviation, array('class' => 'form-control','disabled')) }}
			</div>

			<div class="form-group">
				{{ Form::label('office_name', 'Office Name:') }}{{ $errors->first('office_name', '<span class=errormsg>*:message</span>') }}
				{{ Form::text('office_name', null, array('class' => 'form-control')) }}
			</div>

			@if($office->users()->count())
				<div class="form-group">
					{{ Form::label('office_type', 'Office Type: ') }}
					{{ $errors->first('office_type', '<span class=errormsg>*:message</span>') }}
					<b class="errormsg"> uneditable due to the office having at least one member </b>
					<br />
				
						{{ Form::radio('office_type', 'Central Office', 1,['disabled']) }} Central Office<br>
				
						{{ Form::radio('office_type', 'Field Office', 0,['disabled']) }} Field Office
						{{Form::hidden('office_type',$office->office_type)}}
					
				</div>
				<div class="form-group">
					{{ Form::label('office_flag', 'Option: ') }}
					{{ $errors->first('office_flag') }}
					<b class="errormsg"> uneditable due to the office having at least one member </b>
					<br />

					<input type="checkbox" name="office_flag" id="myCheck"> Disable<br>

					
				</div>
			@else
				<div class="form-group">
					{{ Form::label('office_type', 'Office Type: ') }}
					{{ $errors->first('office_type', '<span class=errormsg>*:message</span>') }}
					<br />
					{{ Form::radio('office_type', 'Central Office') }} Central Office<br>
					{{ Form::radio('office_type', 'Field Office') }} Field Office
				</div>
				<div class="form-group">
					{{ Form::label('office_flag', 'Option: ') }}
					<br />
					{{ Form::checkbox('office_flag', '1') }} Disable<br>
					<input type="checkbox" class="hidden" name="office_flag" id="myCheck">
					{{ $errors->first('office_flag') }}
				</div>
			@endif

			
	

	{{ Form::submit('Save Changes', array('class' => 'btn btn-primary')) }}
	{{ link_to( '/offices', 'Cancel', array('class'=>'btn btn-default') ) }}
	{{ Form::close() }}
	
		</div>
	</div>
@stop
@section('cssjs')

<script type = "text/javascript">
  $(document).ready(function() {
  		document.getElementById("myCheck").disabled=true;
		
  });
</script>

@stop

app/views/administration/edituser.blade.php
@extends('layouts.default')
@section('content')
	<h2>Edit User: {{ $editUser->firstName }} {{ $editUser->lastName }} </h2>
	<hr />
	{{ Form::open(['url' => "/edituser/$editUser->id", 'name' => 'create1', 'class' => 'form-horizontal col-md-6', 'role' => 'form']) }}
		<div class = "form-group">
			{{ Form::label('username', 'Username:'); }}
			{{ $errors->first('username', '<span class=errormsg>*:message</span>') }}
			{{ Form::text('username', $editUser->username, ['class' => 'form-control', 'placeholder' => 'Enter Username', 'disabled' => 'disabled']) }}
		</div>
		<div class = "form-group">
			{{ Form::label('firstName', 'First Name:'); }}
			{{ $errors->first('first_name', '<span class=errormsg>*:message</span>') }}
			{{ Form::text('first_name', $editUser->firstName, ['class' => 'form-control', 'placeholder' => 'Enter First Name']) }}
		</div>
		<div class = "form-group">
			{{ Form::label('lastName', 'Last Name:'); }}
			{{ $errors->first('last_name', '<span class=errormsg>*:message</span>') }}
			{{ Form::text('last_name', $editUser->lastName, ['class' => 'form-control', 'placeholder' => 'Enter Last Name']) }}
		</div>
		<div class = "form-group">
			{{ Form::label('email', 'Email Address:'); }}
			{{ $errors->first('email', '<span class=errormsg>*:message</span>') }}
			{{ Form::text('email', $editUser->email, ['class' => 'form-control', 'placeholder' => 'Enter Email Address']) }}
		</div>
		<hr/>
		<div class = "form-group">
			{{ Form::label('password', 'Password:'); }} <span class="descriptionMsg">(Leave empty to retain the password.)</span>
			{{ $errors->first('password', '<span class=errormsg>*:message</span>') }}
			{{ Form::password('password', ['class' => 'form-control', 'placeholder' => 'Enter Password']) }}
		</div>
		<div class = "form-group">
			{{ Form::label('cpassword', 'Confirm Password:'); }}
			{{ $errors->first('cpassword', '<span class=errormsg>*:message</span>') }}
			{{ Form::password('cpassword', ['class' => 'form-control', 'placeholder' => 'Confirm Password']) }}
		</div>
		<div class = "form-group">
				{{ Form::label('role', 'Role: *'); }}
				{{ $errors->first('role', '<span class=errormsg>*:message</span>') }}
				{{ Form::select('role', $roles, $editUser->role, ['id' => 'roles', 'class' => 'form-control roles']) }}
		</div>
		<div id="osm" class="form-group">
			{{ Form::label('offices', 'Office:'); }}
			{{ $errors->first('office', '<span class=errormsg>*:message</span>') }}
			{{ Form::select('office[]', $osm, $editUser->office_id, ['class' => 'form-control offices']) }}
		</div>
		<div id="fo" class="form-group">
			{{ Form::label('offices', 'Office:'); }}
			{{ $errors->first('office', '<span class=errormsg>*:message</span>') }}
			{{ Form::select('office[]', $fo, $editUser->office_id, ['class' => 'form-control offices']) }}
		</div>
		<div id="co" class="form-group">
			{{ Form::label('offices', 'Office:'); }}
			{{ $errors->first('office', '<span class=errormsg>*:message</span>') }}
			{{ Form::select('office[]', $co, $editUser->office_id, ['class' => 'form-control offices']) }}
		</div>
		<div class="form-group">
			{{ Form::label('user_disabled', 'Disable: ') }}
			<br />
			@if($editUser->disabled)
				{{ Form::checkbox('user_disabled', 0) }} Enable<br>
			@else
				{{ Form::checkbox('user_disabled', 1) }} Disable<br>
			@endif	
		</div>
		<div class = "form-inline form-group">
			{{ Form::submit('Save Changes', ['name' => 'create1', 'class' => 'btn btn-primary', 'id' => 'create1']) }}
			{{ link_to( '/users', 'Cancel', array('class'=>'btn btn-default') ) }}
		</div>
		
	{{ Form::close() }}
</div>
</div>
@stop

@section('cssjs')
<script type="text/javascript">
    $(document).ready(function() {
    	switch($('#roles').val())
    	{
    		case '0': 
    			$('#osm').show();
    			$('#fo').hide();
    			$('#co').hide();
			break;
    		case '1': 
    		case '3':
    			$('#osm').hide();
    			$('#fo').show();
    			$('#co').hide();
			break;
    		case '2': 
    		case '4':
    			$('#osm').hide();
    			$('#fo').hide();
    			$('#co').show();
			break;
			case '5':
    			$('#osm').hide();
    			$('#fo').hide();
    			$('#co').hide();
    		break;
    	}
        $('#roles').change(function(event) {
        	switch($(this).val())
        	{
        		case '0': 
        			$('#osm').show();
        			$('#fo').hide();
        			$('#co').hide();
    			break;
        		case '1': 
        		case '3':
        			$('#osm').hide();
        			$('#fo').show();
        			$('#co').hide();
    			break;
        		case '2': 
        		case '4':
        			$('#osm').hide();
        			$('#fo').hide();
        			$('#co').show();
    			break;
				case '5':
	    			$('#osm').hide();
	    			$('#fo').hide();
	    			$('#co').hide();
	    		break;
        	}
        });
    });
</script>
@stop

app/views/administration/offices.blade.php
@extends('layouts.default')
@section('content')
<h2>Manage Offices</h2>
<hr />
<div class="row" id="testcase">
	<div class="col-md-12">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<i class="fa fa-table fw"></i> Offices
				<div class="pull-right">
					{{ HTML::decode(link_to_route('createoffice.create', '<i class="fa fa-plus fw"></i> Create Office', null,null)) }}
				</div>
			</div>
			<div class="panel-body remove-padding">
				<table class="table table-striped table-hover table-select">
					<thead>
						<tr>
							<th class="width-20">Abbreviation</th>
							<th class="width-40">Office Name</th>
							<th class="width-20">Office Type</th>
							<th class="width-20">Action</th>
						</tr>
					</thead>
					
					<tbody>
						@if(count($offices))
							@foreach($offices as $office)
								@if($office->office_flag==1)
									<tr>
										<td class="strike">{{$office->office_abbreviation}}</td>
										<td class="strike">{{$office->office_name}}</td>
										<td class="strike">{{$office->office_type}}</td>
										<td>
											<div class="btn-group actions">
											    {{ HTML::decode(link_to("createoffice.edit", '<i class="fa fa-pencil fw"></i>', array('class' => 'btn btn-default action-btn hide-button-style', 'title' => 'Edit'))) }}
											</div>
										</td>

									</tr>
								@else
									<tr>
										<td>{{$office->office_abbreviation}}</td>
										<td>{{$office->office_name}}</td>
										<td>{{$office->office_type == "OSM" ? "Central Office" : $office->office_type}}</td>
										<td>
											<div class="btn-group actions">
											    {{ HTML::decode(link_to_route('createoffice.edit', '<i class="fa fa-pencil fw"></i>', $office->id, array('class' => 'btn btn-default action-btn hide-button-style', 'title' => 'Edit'))) }}
											</div>
										</td>
									</tr>
								@endif
							@endforeach
						@else
							<tr>
								<td colspan="4">No office</td>
							</tr>
						@endif
					</tbody>
				</table>
			</div>
			<div class="panel-footer">
				<span class="pull-right"><?php echo $offices->links(); ?></span>
			</div>
		</div>
	</div>
</div>
@stop